[package]
name = "umineko-protocol-ssh"
description = "SSH"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
umineko-protocol-ip = { workspace = true, default-features = true }
umineko-protocol-tcp = { workspace = true, default-features = true }
umineko-protocol-uds = { workspace = true, default-features = true }
umineko-hash-sha = { workspace = true, features = ["sha1", "sha2"] }
umineko-hash-crc = { workspace = true, features = ["adler32"] }
umineko-crypto-hmac = { workspace = true }
umineko-crypto-aes = { workspace = true }
umineko-crypto-chacha20 = { workspace = true }
umineko-crypto-poly1305 = { workspace = true }
umineko-crypto-dh = { workspace = true }
umineko-crypto-ecdh = { workspace = true }
umineko-crypto-mlkem = { workspace = true }
umineko-crypto-eddsa = { workspace = true }
umineko-crypto-ecdsa = { workspace = true }
umineko-crypto-rsa = { workspace = true }
umineko-crypto-mldsa = { workspace = true }
umineko-codec-base = { workspace = true, features = ["base64"] }
umineko-codec-deflate = { workspace = true, default-features = true }
