[package]
name = "umineko-crypto-ecdsa"
description = "ECDSA"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
umineko-hash-sha = { workspace = true, features = ["sha2"] }
umineko-crypto-hmac = { workspace = true }
umineko-helpers = { workspace = true }
