[package]
name = "umineko-protocol-icmp"
description = "ICMP"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
umineko-protocol-ip = { workspace = true, default-features = true }
umineko-helpers = { workspace = true }
