[package]
name = "umineko-protocol-tls"
description = "TLS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["tls10", "tls11", "tls12", "tls13", "dtls", "mtls", "quic"]
tls10 = []
tls11 = []
tls12 = []
tls13 = []
dtls = []
mtls = []
quic = []

[dependencies]
umineko-helpers = { workspace = true }
