[package]
name = "umineko-provider-netbsd"
description = "NetBSD provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
umineko-provider = { workspace = true }
umineko-provider-posix = { workspace = true }
umineko-protocol-ip = { workspace = true, default-features = true, optional = true }
umineko-protocol-icmp = { workspace = true, default-features = true, optional = true }
umineko-protocol-uds = { workspace = true, default-features = true, optional = true }
umineko-protocol-tcp = { workspace = true, default-features = true, optional = true }
umineko-protocol-udp = { workspace = true, default-features = true, optional = true }
umineko-protocol-tls = { workspace = true, default-features = true, optional = true }

[features]
default = ["ip", "icmp", "uds", "tcp", "udp", "hash", "crypto", "tls"]
ip = ["umineko-provider/ip", "umineko-provider-posix/ip", "dep:umineko-protocol-ip"]
icmp = ["umineko-provider/icmp", "umineko-provider-posix/icmp", "dep:umineko-protocol-icmp", "dep:umineko-protocol-ip"]
uds = ["umineko-provider/uds", "umineko-provider-posix/uds", "dep:umineko-protocol-uds"]
tcp = ["umineko-provider/tcp", "umineko-provider-posix/tcp", "dep:umineko-protocol-tcp"]
udp = ["umineko-provider/udp", "umineko-provider-posix/udp", "dep:umineko-protocol-udp"]
hash = ["umineko-provider/hash"]
crypto = ["umineko-provider/crypto"]
tls = ["umineko-provider/tls", "dep:umineko-protocol-tls"]
