[package]
name = "umineko-crypto-slhdsa"
description = "SLH-DSA"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
umineko-helpers = { workspace = true }
umineko-hash-sha = { workspace = true, default-features = true }

[dev-dependencies]
umineko-hash-sha = { workspace = true, default-features = true }
