use alloc::string::String;
use core::fmt;

use umineko_helpers::provider::ProviderError;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum KerberosErrorCode {
    None,
    NameExpired,
    ServiceExpired,
    BadProtocolVersion,
    ClientOldMasterKeyVersion,
    ServerOldMasterKeyVersion,
    ClientPrincipalUnknown,
    ServerPrincipalUnknown,
    PrincipalNotUnique,
    NullKey,
    CannotPostdate,
    NeverValid,
    Policy,
    BadOption,
    EncryptionTypeNotSupported,
    ChecksumTypeNotSupported,
    PreauthenticationTypeNotSupported,
    TransitedTypeNotSupported,
    ClientRevoked,
    ServiceRevoked,
    TGTRevoked,
    ClientNotYetValid,
    ServiceNotYetValid,
    KeyExpired,
    PreauthenticationFailed,
    PreauthenticationRequired,
    ServerNoMatch,
    MustUseUserToUser,
    PathNotAccepted,
    ServiceUnavailable,
    BadIntegrity,
    TicketExpired,
    TicketNotYetValid,
    Repeat,
    NotUs,
    BadMatch,
    Skew,
    BadAddress,
    BadVersion,
    MessageType,
    Modified,
    BadOrder,
    BadKeyVersion,
    NoKey,
    MutualFailed,
    BadDirection,
    Method,
    BadSequence,
    InappropriateChecksum,
    APPathNotAccepted,
    ResponseTooBig,
    Generic,
    FieldTooLong,
    ClientNotTrusted,
    KDCNotTrusted,
    InvalidSignature,
    KeyTooWeak,
    CertificateMismatch,
    NoTGT,
    WrongRealm,
    UserToUserRequired,
    CantVerifyCertificate,
    InvalidCertificate,
    RevokedCertificate,
    RevocationStatusUnknown,
    RevocationStatusUnavailable,
    ClientNameMismatch,
    KDCNameMismatch,
    InconsistentKeyPurpose,
    DigestInCertificateNotAccepted,
    PreauthenticationChecksumRequired,
    DigestInSignedDataNotAccepted,
    PublicKeyEncryptionNotSupported,
    PreauthenticationExpired,
    MorePreauthenticationDataRequired,
    PreauthenticationBadAuthenticationSet,
    UnknownCriticalFASTOptions,
    Unknown(i32),
}

impl KerberosErrorCode {
    pub const ALL: [Self; 77] = [
        Self::None,
        Self::NameExpired,
        Self::ServiceExpired,
        Self::BadProtocolVersion,
        Self::ClientOldMasterKeyVersion,
        Self::ServerOldMasterKeyVersion,
        Self::ClientPrincipalUnknown,
        Self::ServerPrincipalUnknown,
        Self::PrincipalNotUnique,
        Self::NullKey,
        Self::CannotPostdate,
        Self::NeverValid,
        Self::Policy,
        Self::BadOption,
        Self::EncryptionTypeNotSupported,
        Self::ChecksumTypeNotSupported,
        Self::PreauthenticationTypeNotSupported,
        Self::TransitedTypeNotSupported,
        Self::ClientRevoked,
        Self::ServiceRevoked,
        Self::TGTRevoked,
        Self::ClientNotYetValid,
        Self::ServiceNotYetValid,
        Self::KeyExpired,
        Self::PreauthenticationFailed,
        Self::PreauthenticationRequired,
        Self::ServerNoMatch,
        Self::MustUseUserToUser,
        Self::PathNotAccepted,
        Self::ServiceUnavailable,
        Self::BadIntegrity,
        Self::TicketExpired,
        Self::TicketNotYetValid,
        Self::Repeat,
        Self::NotUs,
        Self::BadMatch,
        Self::Skew,
        Self::BadAddress,
        Self::BadVersion,
        Self::MessageType,
        Self::Modified,
        Self::BadOrder,
        Self::BadKeyVersion,
        Self::NoKey,
        Self::MutualFailed,
        Self::BadDirection,
        Self::Method,
        Self::BadSequence,
        Self::InappropriateChecksum,
        Self::APPathNotAccepted,
        Self::ResponseTooBig,
        Self::Generic,
        Self::FieldTooLong,
        Self::ClientNotTrusted,
        Self::KDCNotTrusted,
        Self::InvalidSignature,
        Self::KeyTooWeak,
        Self::CertificateMismatch,
        Self::NoTGT,
        Self::WrongRealm,
        Self::UserToUserRequired,
        Self::CantVerifyCertificate,
        Self::InvalidCertificate,
        Self::RevokedCertificate,
        Self::RevocationStatusUnknown,
        Self::RevocationStatusUnavailable,
        Self::ClientNameMismatch,
        Self::KDCNameMismatch,
        Self::InconsistentKeyPurpose,
        Self::DigestInCertificateNotAccepted,
        Self::PreauthenticationChecksumRequired,
        Self::DigestInSignedDataNotAccepted,
        Self::PublicKeyEncryptionNotSupported,
        Self::PreauthenticationExpired,
        Self::MorePreauthenticationDataRequired,
        Self::PreauthenticationBadAuthenticationSet,
        Self::UnknownCriticalFASTOptions,
    ];

    pub fn number(&self) -> i32 {
        match self {
            Self::None => 0,
            Self::NameExpired => 1,
            Self::ServiceExpired => 2,
            Self::BadProtocolVersion => 3,
            Self::ClientOldMasterKeyVersion => 4,
            Self::ServerOldMasterKeyVersion => 5,
            Self::ClientPrincipalUnknown => 6,
            Self::ServerPrincipalUnknown => 7,
            Self::PrincipalNotUnique => 8,
            Self::NullKey => 9,
            Self::CannotPostdate => 10,
            Self::NeverValid => 11,
            Self::Policy => 12,
            Self::BadOption => 13,
            Self::EncryptionTypeNotSupported => 14,
            Self::ChecksumTypeNotSupported => 15,
            Self::PreauthenticationTypeNotSupported => 16,
            Self::TransitedTypeNotSupported => 17,
            Self::ClientRevoked => 18,
            Self::ServiceRevoked => 19,
            Self::TGTRevoked => 20,
            Self::ClientNotYetValid => 21,
            Self::ServiceNotYetValid => 22,
            Self::KeyExpired => 23,
            Self::PreauthenticationFailed => 24,
            Self::PreauthenticationRequired => 25,
            Self::ServerNoMatch => 26,
            Self::MustUseUserToUser => 27,
            Self::PathNotAccepted => 28,
            Self::ServiceUnavailable => 29,
            Self::BadIntegrity => 31,
            Self::TicketExpired => 32,
            Self::TicketNotYetValid => 33,
            Self::Repeat => 34,
            Self::NotUs => 35,
            Self::BadMatch => 36,
            Self::Skew => 37,
            Self::BadAddress => 38,
            Self::BadVersion => 39,
            Self::MessageType => 40,
            Self::Modified => 41,
            Self::BadOrder => 42,
            Self::BadKeyVersion => 44,
            Self::NoKey => 45,
            Self::MutualFailed => 46,
            Self::BadDirection => 47,
            Self::Method => 48,
            Self::BadSequence => 49,
            Self::InappropriateChecksum => 50,
            Self::APPathNotAccepted => 51,
            Self::ResponseTooBig => 52,
            Self::Generic => 60,
            Self::FieldTooLong => 61,
            Self::ClientNotTrusted => 62,
            Self::KDCNotTrusted => 63,
            Self::InvalidSignature => 64,
            Self::KeyTooWeak => 65,
            Self::CertificateMismatch => 66,
            Self::NoTGT => 67,
            Self::WrongRealm => 68,
            Self::UserToUserRequired => 69,
            Self::CantVerifyCertificate => 70,
            Self::InvalidCertificate => 71,
            Self::RevokedCertificate => 72,
            Self::RevocationStatusUnknown => 73,
            Self::RevocationStatusUnavailable => 74,
            Self::ClientNameMismatch => 75,
            Self::KDCNameMismatch => 76,
            Self::InconsistentKeyPurpose => 77,
            Self::DigestInCertificateNotAccepted => 78,
            Self::PreauthenticationChecksumRequired => 79,
            Self::DigestInSignedDataNotAccepted => 80,
            Self::PublicKeyEncryptionNotSupported => 81,
            Self::PreauthenticationExpired => 90,
            Self::MorePreauthenticationDataRequired => 91,
            Self::PreauthenticationBadAuthenticationSet => 92,
            Self::UnknownCriticalFASTOptions => 93,
            Self::Unknown(number) => *number,
        }
    }

    pub fn from_number(number: i32) -> Self {
        Self::ALL.iter().copied().find(|code| code.number() == number).unwrap_or(Self::Unknown(number))
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::None => "KDC_ERR_NONE",
            Self::NameExpired => "KDC_ERR_NAME_EXP",
            Self::ServiceExpired => "KDC_ERR_SERVICE_EXP",
            Self::BadProtocolVersion => "KDC_ERR_BAD_PVNO",
            Self::ClientOldMasterKeyVersion => "KDC_ERR_C_OLD_MAST_KVNO",
            Self::ServerOldMasterKeyVersion => "KDC_ERR_S_OLD_MAST_KVNO",
            Self::ClientPrincipalUnknown => "KDC_ERR_C_PRINCIPAL_UNKNOWN",
            Self::ServerPrincipalUnknown => "KDC_ERR_S_PRINCIPAL_UNKNOWN",
            Self::PrincipalNotUnique => "KDC_ERR_PRINCIPAL_NOT_UNIQUE",
            Self::NullKey => "KDC_ERR_NULL_KEY",
            Self::CannotPostdate => "KDC_ERR_CANNOT_POSTDATE",
            Self::NeverValid => "KDC_ERR_NEVER_VALID",
            Self::Policy => "KDC_ERR_POLICY",
            Self::BadOption => "KDC_ERR_BADOPTION",
            Self::EncryptionTypeNotSupported => "KDC_ERR_ETYPE_NOSUPP",
            Self::ChecksumTypeNotSupported => "KDC_ERR_SUMTYPE_NOSUPP",
            Self::PreauthenticationTypeNotSupported => "KDC_ERR_PADATA_TYPE_NOSUPP",
            Self::TransitedTypeNotSupported => "KDC_ERR_TRTYPE_NOSUPP",
            Self::ClientRevoked => "KDC_ERR_CLIENT_REVOKED",
            Self::ServiceRevoked => "KDC_ERR_SERVICE_REVOKED",
            Self::TGTRevoked => "KDC_ERR_TGT_REVOKED",
            Self::ClientNotYetValid => "KDC_ERR_CLIENT_NOTYET",
            Self::ServiceNotYetValid => "KDC_ERR_SERVICE_NOTYET",
            Self::KeyExpired => "KDC_ERR_KEY_EXPIRED",
            Self::PreauthenticationFailed => "KDC_ERR_PREAUTH_FAILED",
            Self::PreauthenticationRequired => "KDC_ERR_PREAUTH_REQUIRED",
            Self::ServerNoMatch => "KDC_ERR_SERVER_NOMATCH",
            Self::MustUseUserToUser => "KDC_ERR_MUST_USE_USER2USER",
            Self::PathNotAccepted => "KDC_ERR_PATH_NOT_ACCEPTED",
            Self::ServiceUnavailable => "KDC_ERR_SVC_UNAVAILABLE",
            Self::BadIntegrity => "KRB_AP_ERR_BAD_INTEGRITY",
            Self::TicketExpired => "KRB_AP_ERR_TKT_EXPIRED",
            Self::TicketNotYetValid => "KRB_AP_ERR_TKT_NYV",
            Self::Repeat => "KRB_AP_ERR_REPEAT",
            Self::NotUs => "KRB_AP_ERR_NOT_US",
            Self::BadMatch => "KRB_AP_ERR_BADMATCH",
            Self::Skew => "KRB_AP_ERR_SKEW",
            Self::BadAddress => "KRB_AP_ERR_BADADDR",
            Self::BadVersion => "KRB_AP_ERR_BADVERSION",
            Self::MessageType => "KRB_AP_ERR_MSG_TYPE",
            Self::Modified => "KRB_AP_ERR_MODIFIED",
            Self::BadOrder => "KRB_AP_ERR_BADORDER",
            Self::BadKeyVersion => "KRB_AP_ERR_BADKEYVER",
            Self::NoKey => "KRB_AP_ERR_NOKEY",
            Self::MutualFailed => "KRB_AP_ERR_MUT_FAIL",
            Self::BadDirection => "KRB_AP_ERR_BADDIRECTION",
            Self::Method => "KRB_AP_ERR_METHOD",
            Self::BadSequence => "KRB_AP_ERR_BADSEQ",
            Self::InappropriateChecksum => "KRB_AP_ERR_INAPP_CKSUM",
            Self::APPathNotAccepted => "KRB_AP_PATH_NOT_ACCEPTED",
            Self::ResponseTooBig => "KRB_ERR_RESPONSE_TOO_BIG",
            Self::Generic => "KRB_ERR_GENERIC",
            Self::FieldTooLong => "KRB_ERR_FIELD_TOOLONG",
            Self::ClientNotTrusted => "KDC_ERROR_CLIENT_NOT_TRUSTED",
            Self::KDCNotTrusted => "KDC_ERROR_KDC_NOT_TRUSTED",
            Self::InvalidSignature => "KDC_ERROR_INVALID_SIG",
            Self::KeyTooWeak => "KDC_ERR_KEY_TOO_WEAK",
            Self::CertificateMismatch => "KDC_ERR_CERTIFICATE_MISMATCH",
            Self::NoTGT => "KRB_AP_ERR_NO_TGT",
            Self::WrongRealm => "KDC_ERR_WRONG_REALM",
            Self::UserToUserRequired => "KRB_AP_ERR_USER_TO_USER_REQUIRED",
            Self::CantVerifyCertificate => "KDC_ERR_CANT_VERIFY_CERTIFICATE",
            Self::InvalidCertificate => "KDC_ERR_INVALID_CERTIFICATE",
            Self::RevokedCertificate => "KDC_ERR_REVOKED_CERTIFICATE",
            Self::RevocationStatusUnknown => "KDC_ERR_REVOCATION_STATUS_UNKNOWN",
            Self::RevocationStatusUnavailable => "KDC_ERR_REVOCATION_STATUS_UNAVAILABLE",
            Self::ClientNameMismatch => "KDC_ERR_CLIENT_NAME_MISMATCH",
            Self::KDCNameMismatch => "KDC_ERR_KDC_NAME_MISMATCH",
            Self::InconsistentKeyPurpose => "KDC_ERR_INCONSISTENT_KEY_PURPOSE",
            Self::DigestInCertificateNotAccepted => "KDC_ERR_DIGEST_IN_CERT_NOT_ACCEPTED",
            Self::PreauthenticationChecksumRequired => "KDC_ERR_PA_CHECKSUM_MUST_BE_INCLUDED",
            Self::DigestInSignedDataNotAccepted => "KDC_ERR_DIGEST_IN_SIGNED_DATA_NOT_ACCEPTED",
            Self::PublicKeyEncryptionNotSupported => "KDC_ERR_PUBLIC_KEY_ENCRYPTION_NOT_SUPPORTED",
            Self::PreauthenticationExpired => "KDC_ERR_PREAUTH_EXPIRED",
            Self::MorePreauthenticationDataRequired => "KDC_ERR_MORE_PREAUTH_DATA_REQUIRED",
            Self::PreauthenticationBadAuthenticationSet => "KDC_ERR_PREAUTH_BAD_AUTHENTICATION_SET",
            Self::UnknownCriticalFASTOptions => "KDC_ERR_UNKNOWN_CRITICAL_FAST_OPTIONS",
            Self::Unknown(_) => "UNKNOWN",
        }
    }

    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|code| code.as_str() == name)
    }
}

impl fmt::Display for KerberosErrorCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum KerberosError {
    Version,
    Message,
    Encoding,
    EncryptionType,
    ChecksumType,
    Key,
    Integrity,
    Principal(String),
    Realm(String),
    Ticket,
    Skew,
    Replay,
    Code(KerberosErrorCode),
    State,
    Limit,
    Transport,
    Provider(ProviderError),
    Timeout,
}

impl fmt::Display for KerberosError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        todo!()
    }
}

impl core::error::Error for KerberosError {}

impl From<KerberosErrorCode> for KerberosError {
    fn from(code: KerberosErrorCode) -> Self {
        Self::Code(code)
    }
}

impl From<ProviderError> for KerberosError {
    fn from(error: ProviderError) -> Self {
        Self::Provider(error)
    }
}
