[package]
name = "umineko-protocol-mail"
description = "Mail authentication"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
umineko-protocol-dns = { workspace = true, default-features = true }

[features]
default = ["spf", "dkim", "dmarc", "bimi"]
spf = []
dkim = []
dmarc = []
bimi = []
